name: DevSecOps Security Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec (IaC Scan)
        uses: aquasecurity/tfsec-action@v1.0.1

      - name: Trivy FS Scan (source code)
        uses: aquasecurity/trivy-action@0.11.0
        with:
          scan-type: fs
          format: table
          severity: CRITICAL
          exit-code: 1
          output: trivy-fs.txt

      - name: Build Docker Image
        run: docker build -t app:test.

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app:test
          format: table
          severity: CRITICAL
          exit-code: 1
          output: trivy-image.txt
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Terraform directory
        run: |
          echo "Listing FarmSafe folder"
          ls -la ./FarmSafe || true

      - name: Run tfsec on IaC
        uses: aquasecurity/tfsec-action@master
        with:
          path: Group8-devops/FarmSafe

          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: 'CRITICAL,HIGH'
          exit-code: 1
          format: sarif
          output: trivy-results.sarif

        - name:  Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()  # Upload even if previous step fails
        with:
          sarif_file: trivy-results.sarif

      # Generate readable report (always runs)
      - name: Generate Trivy report
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          scan-type: fs
          format: table
          output: trivy-fs.txt
