name: DevSecOps Security Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec (IaC Scan)
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Trivy FS Scan (source code)
        uses: aquasecurity/trivy-action@v0.8.0
        with:
          scan-type: fs
          format: table
          severity: CRITICAL
          exit-code: 1
          output: trivy-fs.txt

      - name: Build Docker Image
        run: docker build -t app:test .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.8.0
        with:
          image-ref: app:test
          format: table
          severity: CRITICAL
          exit-code: 1
          output: trivy-image.txt
